//! The board as a page.
//!
//! **D23** already promised this: a LAN page reached by a QR code, showing
//! latched numbers. What is new is that the page does not lay itself out — it
//! draws the same frame a panel would take, on the same pitch, with the unlit
//! diodes drawn too. So it is a *preview* of a board rather than a second design
//! that will have to be reconciled with one.
//!
//! One file, nothing fetched, no server. Until race control has an HTTP surface
//! this writes to disk; when it grows one, the same bytes go out of it.

use std::fmt::Write;

use crate::{Board, Frame};

const CSS: &str = include_str!("../assets/board.css");
const JS: &str = include_str!("../assets/board.js");

fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

/// One state the board was in, and when it started being in it.
pub struct Shot {
    pub t_ms: u64,
    pub show: String,
    pub frame: Frame,
}

/// The page's content, with no document wrapper.
pub fn body(board: Board, title: &str, source: &str, shots: &[Shot]) -> String {
    let frames: Vec<String> = shots
        .iter()
        .map(|s| {
            format!(
                "{{\"t\":{},\"show\":\"{}\",\"bits\":\"{}\"}}",
                s.t_ms,
                s.show
                    .chars()
                    .filter(|c| c.is_ascii_alphanumeric() || *c == '-')
                    .collect::<String>(),
                s.frame.hex()
            )
        })
        .collect();

    let mut out = String::new();
    let _ = write!(
        out,
        r#"<div class="top">
  <h1>beam402 <span>scoreboard</span></h1>
  <div class="meta">{title}</div>
  <div class="meta">{source}</div>
  <div class="warn">simulated · no board exists</div>
</div>

<div class="panel"><canvas id="panel" aria-label="the scoreboard"></canvas></div>

<div class="transport">
  <button id="play" type="button">play</button>
  <input id="scrub" type="range" min="0" value="0" step="1" aria-label="board state"/>
  <div class="clock"><span id="secs">0.0</span><small> s</small></div>
  <div class="pill" id="show">idle</div>
</div>

<div class="notes">
  <div>
    <h2>Resolution</h2>
    <b>{w} × {h}</b>, {lanes} bands of {band} rows. That is a whole number of the
    32 × 16 module every LED sign is assembled from — four across and two down
    per lane. Nothing has been bought: <b>D15</b> gates that until the bench
    answers. The number is here so that “does it fit” is a test rather than a
    discovery once panels arrive.
  </div>
  <div>
    <h2>What it will not show</h2>
    While a round is running the board says <b>RUN</b>, not the last pair's
    numbers. A spectator who reads a stale ET as this round's is certain of the
    wrong thing, and certainty is the one thing a scoreboard is for.
  </div>
  <div>
    <h2>What it costs</h2>
    A band spends <b>7 + 14 + 7</b> rows on the dial line, the ET at double size
    and the reaction-and-speed line, plus one for the separator. That is 29 of
    32: there is <b>no fourth line</b>. The next field somebody wants — 60 ft, a
    class, a driver's name — buys a taller band, which buys more panels.
  </div>
  <div>
    <h2>The bar, not the word</h2>
    Who won is a solid bar down the edge of the band. It reads from a distance
    where three letters do not, and it costs no characters in a row that has
    none to spare.
  </div>
</div>

<footer>
  Generated by <code>beam402 scoreboard</code>. Every number came from a scenario
  file that stated it; nothing in this project has run against hardware.
</footer>

<style>{css}</style>
<script>window.BOARD={{"w":{w},"h":{h},"frames":[{frames}]}};</script>
<script>{js}</script>
"#,
        title = esc(title),
        source = esc(source),
        w = board.w,
        h = board.height(),
        band = board.band,
        lanes = board.lanes,
        css = CSS,
        js = JS,
        frames = frames.join(","),
    );
    out
}

/// A standalone document.
pub fn page(board: Board, title: &str, source: &str, shots: &[Shot]) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{t} — beam402 scoreboard</title>
<style>*{{box-sizing:border-box}}body{{margin:0}}</style>
</head>
<body>
{body}
</body>
</html>
"#,
        t = esc(title),
        body = body(board, title, source, shots)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shots() -> Vec<Shot> {
        vec![Shot {
            t_ms: 0,
            show: "result".into(),
            frame: {
                let mut f = Frame::new(16, 8);
                f.text(0, 0, "8", 1);
                f
            },
        }]
    }

    #[test]
    fn the_page_reaches_for_nothing_outside_itself() {
        let html = page(Board::REFERENCE, "Sim Strip", "s", &shots());
        for reach in ["http://", "https://", "fetch(", "<link", "<img"] {
            assert!(!html.contains(reach), "the page reaches for {reach}");
        }
    }

    #[test]
    fn a_hostile_venue_name_cannot_become_markup() {
        // The title comes from a mapping file, and a mapping file travels.
        let html = page(Board::REFERENCE, "<script>alert(1)</script>", "s", &shots());
        assert!(!html.contains("<script>alert(1)"));
        assert!(html.contains("&lt;script&gt;"));
    }

    #[test]
    fn the_frames_carry_the_pixels_and_nothing_else() {
        // The payload a panel would take: hex, row-major, no layout.
        let html = page(Board::REFERENCE, "x", "s", &shots());
        assert!(html.contains("\"bits\":\""), "{html:.400}");
        assert!(html.contains("\"w\":128,\"h\":64"));
    }
}
