//! The page.
//!
//! Two entry points: [`body`] emits the content on its own, for embedding, and
//! [`page`] wraps it in a minimal standalone document. Both are one file with
//! everything inlined — no CDN, no server, no fetch — so a scope page opens from
//! a `file://` URL, survives being emailed, and can be committed beside the round
//! it is evidence about.

use std::fmt::Write;

use crate::Capture;

const CSS: &str = include_str!("../assets/scope.css");
const JS: &str = include_str!("../assets/scope.js");

/// Anything that came from a file, on its way into markup.
///
/// The venue name and the node labels are the mapping file's, and a mapping file
/// travels between clubs (`protocol.md` §5). The JS escapes what it interpolates;
/// this escapes what is written into the skeleton, so both paths are closed.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

/// The page's content, with no document wrapper.
pub fn body(c: &Capture) -> String {
    let mut s = String::new();
    let dials = match c.dials {
        Some((a, b)) => format!(" · dial {a} / {b}"),
        None => String::new(),
    };

    let _ = write!(
        s,
        r#"<div class="top">
  <h1>beam402 <span>scope</span></h1>
  <div class="meta">{venue} · {format}{dials}</div>
  <div class="meta">{source}</div>
  <div class="warn">simulated · no hardware exists</div>
</div>

<div class="strip" id="strip"></div>
<div class="caption">
  Beam crossings are measured. A car between two of them is <em>drawn</em>, by
  interpolating the pair — the same rule the time slip follows, applied to pixels.
  Marks with <b>*</b> are placed by this drawing rather than by the mapping file,
  which records the trap’s base and never where the pair sits.
</div>

<div class="transport">
  <button id="first" type="button">start</button>
  <button id="play" type="button">play</button>
  <button id="last" type="button">end</button>
  <input id="scrub" type="range" min="0" value="0" step="1" aria-label="timeline"/>
  <div class="clock" id="clock">0.0<small> s</small></div>
  <div class="pill" id="phase">idle</div>
</div>

<div class="grid">
  <div class="card">
    <h2>Tree</h2>
    <div id="tree"></div>
    <div class="spot" id="where"></div>
  </div>

  <div class="card">
    <h2>Nodes <em>— a set bit is an intact beam (D17)</em></h2>
    <div id="nodes"></div>
    <h2 style="margin-top:14px">The run <em>— measured crossings</em></h2>
    <div id="run"></div>
  </div>

  <div class="card">
    <h2>Events <em>— what the poller decoded</em></h2>
    <div class="tape" id="events"></div>
    <h2 style="margin-top:14px">Bus <em>— <span id="cost"></span></em></h2>
    <div class="tape" id="bus"></div>
  </div>

  <div class="card wide">
    <h2>Time slip</h2>
    <pre class="slip">{slip}</pre>
  </div>
</div>

<footer>
  Generated by <code>beam402 scope</code>. Every number here came from a scenario
  file that stated it; nothing in this project has run against hardware, and by
  <b>D15</b> nothing is claimed about it until the bench answers.
</footer>

<style>{css}</style>
<script>window.CAPTURE={json};</script>
<script>{js}</script>
"#,
        venue = esc(&c.venue),
        format = esc(&c.format),
        dials = esc(&dials),
        source = esc(&c.source),
        slip = esc(&c.slip),
        css = CSS,
        json = c.to_json(),
        js = JS,
    );
    s
}

/// A standalone document, for writing to a file.
pub fn page(c: &Capture) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title} — beam402 scope</title>
<style>*{{box-sizing:border-box}}body{{margin:0}}</style>
</head>
<body>
{body}
</body>
</html>
"#,
        title = esc(&c.title),
        body = body(c)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Capture, Crossing, Frame};

    fn capture(venue: &str) -> Capture {
        Capture {
            title: "t".into(),
            venue: venue.into(),
            lanes: 2,
            finish_m: 402.336,
            beams: vec![],
            labels: vec![(1, venue.to_string())],
            format: "bracket".into(),
            dials: Some((12.34, 7.5)),
            handicap_ms: [0, 4840],
            launch_ms: [Some(0), None],
            crossings: vec![Crossing {
                lane: 1,
                beam: "finish".into(),
                at_m: 402.336,
                t_s: 12.34,
            }],
            frames: vec![Frame::default()],
            slip: "WIN lane 1".into(),
            source: "s".into(),
        }
    }

    #[test]
    fn a_hostile_venue_name_cannot_become_markup() {
        // A mapping file travels between clubs and a scope page is meant to be
        // shared as evidence. Neither is a reason to execute what is in it.
        let html = page(&capture("<script>alert(1)</script>"));
        assert!(
            !html.contains("<script>alert(1)"),
            "escaped in the skeleton"
        );
        assert!(html.contains("&lt;script&gt;alert(1)"));
        // And in the embedded capture, where it is a JSON string in a <script>
        // block, the closing tag is broken up as well.
        assert!(!html.contains("</script>alert"), "no early close");
    }

    #[test]
    fn the_page_reaches_for_nothing_outside_itself() {
        // One file, no CDN, no fetch: it has to open from a file:// URL and
        // survive being emailed.
        let html = page(&capture("Sim Strip"));
        for reach in ["http://", "https://", "fetch(", "XMLHttpRequest", "<link"] {
            assert!(!html.contains(reach), "the page reaches for {reach}");
        }
        assert!(html.contains("window.CAPTURE="));
    }
}
